# Generated by Django 5.0 on 2023-12-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormtemplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
